kind: Deployment
apiVersion: apps/v1
metadata:
  name: multiply-deployment
  labels:
    app: multiply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
    spec:
      containers:
      - name: multiply-http-cont
        image: mahendrakariya/multiply_http:0.0.1
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: multiply-svc
spec:
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
