apiVersion: v1
kind: Pod
metadata:
   name: multiply-pod
spec:
   containers:
   - name: multiply-http-cont
     image: mahendrakariya/multiply_http:0.0.1
     ports:
     - containerPort: 8001
   - name: multiply-http-cont-1
     image: mahendrakariya/add_grpc:0.0.1
     ports:
     - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
   name: multiply-svc
spec:
   ports:
     - protocol: TCP
       port: 8001
       targetPort: 8001
